<h1> Комментарий ревьюера </h1>

Привет, Руслан!
Меня зовут Виктория Ильина, и я буду проверять твой проект. Предлагаю общаться на "ты", но если тебе будет не комфортно, обязательно сообщи и мы перейдем на "вы". 

Моя основная цель - не указать на совершённые тобой ошибки, а поделиться своим опытом и помочь тебе стать специалистом по Data Science. Ты уже проделал большую работу над проектом, но давай сделаем его ещё лучше. Ниже ты найдёшь мои комментарии - пожалуйста, не перемещай, не изменяй и не удаляй их. Я буду использовать различные цвета, чтобы было легче воспринимать мои комментарии:

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера❌:</b> Так выделены самые важные замечания. Без их отработки проект не будет принят.
</div>

<div class="alert alert-block alert-warning">
<b>Комментарий ревьюера🤔:</b> Так выделены небольшие замечания. Одно-два таких замечания в проекте допустимы, но если их будет больше - тебе будет необходимо внести исправления. Однако, если перед нами стоит цель не просто сдать проект и забыть, а приобрести новые знания и успешно применять их в будущем, я бы всё-таки рекомендовала тебе прорабатывать эти недочёты.
</div>
    
<div class="alert alert-block alert-success">
<b>Комментарий ревьюера👍:</b> Так я выделю все остальные комментарии.
</div>
    
Давай работать над проектом в диалоге: если ты что-то меняешь в проекте или отвечаешь на мои комментарии - пиши об этом. Мне будет легче отследить изменения, если ты выделишь свои комментарии:

<div class="alert alert-block alert-info">
<b>Комментарий студента:</b> Например, вот так.
</div>

Давай посмотрим, что получилось!

# Защита персональных данных клиентов
## Описание проекта
Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Инструкция по выполнению проекта

1. Загрузите и изучите данные.
2. Ответьте на вопрос и обоснуйте решение.

Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? (Её можно обучить заново.)
* Изменится. Приведите примеры матриц.
* Не изменится. Укажите, как связаны параметры линейной регрессии в исходной задаче и в преобразованной.
3. Предложите алгоритм преобразования данных для решения задачи. Обоснуйте, почему качество линейной регрессии не поменяется.
4. Запрограммируйте этот алгоритм, применив матричные операции. Проверьте, что качество линейной регрессии из sklearn не отличается до и после преобразования. Примените метрику R2.

## Описание данных
**Признаки**: пол, возраст и зарплата застрахованного, количество членов его семьи.

**Целевой признак**: количество страховых выплат клиенту за последние 5 лет.

## 1. Загрузите и изучите данные.

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

try:
    data = pd.read_csv('insurance.csv')
except:
    data = pd.read_csv('/datasets/insurance.csv')

data

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0       1     41.0   49600.0            1                  0
1       0     46.0   38000.0            1                  1
2       0     29.0   21000.0            0                  0
3       0     21.0   41700.0            2                  0
4       1     28.0   26100.0            0                  0
...   ...      ...       ...          ...                ...
4995    0     28.0   35700.0            2                  0
4996    0     34.0   52400.0            1                  0
4997    0     20.0   33900.0            2                  0
4998    1     22.0   32700.0            3                  0
4999    1     28.0   40600.0            1                  0

[5000 rows x 5 columns]

In [2]:
display(data.info())
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


None

Пол      Возраст      Зарплата  Члены семьи  Страховые выплаты
count  5000.000000  5000.000000   5000.000000  5000.000000        5000.000000
mean      0.499000    30.952800  39916.360000     1.194200           0.148000
std       0.500049     8.440807   9900.083569     1.091387           0.463183
min       0.000000    18.000000   5300.000000     0.000000           0.000000
25%       0.000000    24.000000  33300.000000     0.000000           0.000000
50%       0.000000    30.000000  40200.000000     1.000000           0.000000
75%       1.000000    37.000000  46600.000000     2.000000           0.000000
max       1.000000    65.000000  79000.000000     6.000000           5.000000

Мы видим, что данные изначально полностью готовы к дальнейшему исследованию 

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера👍:</b> Хорошо
    
Этого не было в требованиях к проекту, просто дополнительно по EDA:
    
в таблице данных компании соблюден почти идеальный баланс между мужчинами и женщинами. Средний возраст застрахованного составляет около 31 года, при этом медиана составляет 30. Границы возраста застрахованных приводят к выводу, что компания не занимается страхованием лиц, чей возраст составляет менее 18 и старше 65 лет. Также интересно взглянуть на уровень заработной платы застрахованных - медиана составляет чуть более 40 000 рублей. В целом, в компании скорее представлен средний экономический класс, чем слишком бедные или слишком богатые граждане. 
    
Дополнительно можно было бы посмотреть корреляцию. Возраст и количество страховых выплат клиенту за последние 5 лет имеют корреляцию 0.651. Вероятно, для компании есть взаимосвязь: чем старше застрахованное лицо, тем более вероятно он потребует страховку чаще, следовательно, несёт в себе больше рисков для предприятия.

Если подробнее изучить эту связь, то можно узнать, что все клиенты в возрасте до 42 лет не получали ни одной страховой выплаты, в возрасте до 49 лет только одну выплату, до 55 лет две выплаты, до 59 лет три выплаты, до 65 лет четыре выплаты. Только один клиент получил максимальное количество выплат за пять лет - пять выплат в возрасте 65 лет
</div>

<div class="alert alert-block alert-info">
<b>Комментарий студента:</b> Виктория привет! Спасибо большущее за ревью и за подробную дополнительную информацию! :3
</div>

## 2. Ответьте на вопрос и обоснуйте решение.
**Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? (Её можно обучить заново.)**

__* Изменится. Приведите примеры матриц.__

__* Не изменится. Укажите, как связаны параметры линейной регрессии в исходной задаче и в преобразованной.__

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** Качество линейной регрессии не поменяется

**Обоснование:** 
В преобразованной задаче допустим, что новые предсказания следующие: 

$$
a_1 = X_1w_1, 
$$

где $X_1 = X*P$, которая получится той же размерности, что и матрица $X$

Задача обучения теперь следующая:

$$
w_1 = \arg\min_w MSE(X_1w_1, y)
$$

Формула обучения теперь:

$$
w = (X_1^T X_1)^{-1} X_1^T y
$$

При подстановке $w$ и $w_1$ в $а$ и $а_1$, соответственно, мы получим, что $a1=a=y$. Далее считаем $R^2$ и получаем равные значения

## 3. Предложите алгоритм преобразования данных для решения задачи. Обоснуйте, почему качество линейной регрессии не поменяется.

1. Умножим справа матрицу признаков с размерностью (m х n+1) на рандомную обратимую матрицу с размерностью (n+1 x n+1):
$X_1 = X * P$. $X_1$ получится с размерностью такой же, как и у исходной матрицы $X$ (m х n+1)
2. Докажем, что $a_1 = a$:
$$
a_1 = a => X_1(X_1^T X_1)^{-1} X_1^T y = X (X^T X)^{-1} X^T y => (X_1^T X_1)^{-1} (X_1^T X_1)y = (X^T X)^{-1} (X^T X)y => Ey = Ey => y= y
$$

$$
ЧТД
$$

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера👍:</b> Абсолютно верно, молодец, что не раскрыл $(X^T X)^{-1}$, так как для неквадратных матриц $X$ и $X^T$ обратных матриц не существует. 
</div>


## 4. Запрограммируйте этот алгоритм, применив матричные операции. 
## Проверьте, что качество линейной регрессии из sklearn не отличается до и после преобразования. Примените метрику R2.
Итак, **для начала** мы обучим модель и посчитаем качество модели с помощью MSE и R^2. 

**Далее**, проведем шифрование персональных данных(features) путем умножения на обратимую (должна быть квадратная и невырожденная) матрицу. 

**Наконец**, нужно вновь посмотреть на качество модели и сделать выводы.

Выделим features и target:

In [3]:
features = data.drop('Страховые выплаты', axis=1)
target = data['Страховые выплаты']

Обучим модель до шифрования и оценим ее качество:

In [4]:
model = LinearRegression()
model.fit(features,target)
predictions = model.predict(features)
print(r2_score(target,predictions))

0.4249455028666801


Для того чтобы найти обратимую матрицу, удовлетворяющую условиям, напишем следующую функцию

In [5]:
def get_invertible_random_matrix(n):
    random_matrix = np.random.normal(size=(n, n))
    np.linalg.det(random_matrix) != 0
    return random_matrix

In [6]:
p = get_invertible_random_matrix(features.shape[1])
p

array([[-1.76387473,  2.58445931,  1.09549861, -0.35966903],
       [ 1.95206739, -0.33469851, -0.41727028, -1.1451354 ],
       [ 1.45798748, -0.57697084,  0.5689765 , -0.51014572],
       [-0.40828845,  0.78164482,  0.52749393,  0.8989817 ]])

Проверим полученную матрицу с помощью умножения обратной ей матрицы, а также посмотрим на определитель матрицы

In [7]:
pp = np.linalg.inv(p)
pp

array([[-0.11740548,  0.51951766,  0.02429458,  0.62858311],
       [ 0.1798293 ,  0.63262907, -0.45612418,  0.61896163],
       [ 0.19343805, -0.63650149,  1.04726651, -0.13909982],
       [-0.32318271,  0.05936994, -0.20687899,  0.94129766]])

In [8]:
print(np.linalg.det(p))
print(np.linalg.det(pp))

-4.654768488406792
-0.21483345573267706


In [9]:
p.dot(pp).round()

array([[ 1., -0., -0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0.,  0.,  1., -0.],
       [ 0., -0.,  0.,  1.]])

Теперь умножим матрицу признаков на обратимую матрицу (р) => заново переобучим модель => рассчитаем R^2

In [10]:
features1 = features.dot(p)

model1 = LinearRegression()
model1.fit(features1, target)
predictions1 = model1.predict(features1)
print(r2_score(target, predictions1))

0.42494550286667776


Отлично, как и полагалось, качество модели не изменилось!

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера👍:</b> Верно, таким образом в случае домножения матрицы признаков на случайную обратимую матрицу можно обеспечить защиту данных, не особо потеряв в качестве модели. (Незначительное отличие вызвано особенностью преобразования матриц и чисел с плавающей точкой, это норма)
</div>


<div class="alert alert-block alert-success">
<b>Комментарий ревьюера👍:</b> Спасибо тебе за проделанную работу, ты демонстрируешь отличное владение материалом спринта.
    
Отправляю обратно, чтобы ты мог задать какие-то вопросы, может хочешь какую-то подборку статей.   

Обзоры по применению криптографии в машинном обучении: https://arxiv.org/pdf/1902.04109.pdf, https://www.researchgate.net/publication/342746786_Some_Applications_of_Machine_Learning_in_Cryptography

Небольшой обзор на Шифр Хилла: https://habr.com/ru/post/595281/
   
Примеры использования линейной алгебры в машинном обучении:
https://machinelearningmastery.com/examples-of-linear-algebra-in-machine-learning/
    
Для чего нужна математика в машинном обучении?
https://proglib.io/p/dlya-chego-nuzhen-matematicheskiy-analiz-v-mashinnom-obuchenii-2021-02-15

Большая статья по векторам:
https://neptune.ai/blog/understanding-vectors-from-a-machine-learning-perspective  

Можно ещё дополнительно посмотреть лекции от МФТИ https://www.youtube.com/playlist?list=PLk4h7dmY2eYHHTyfLyrl7HmP-H3mMAW08
    
Классная серия роликов по линейной алгебре на английском (можно включить автоматические русские субтитры): https://www.youtube.com/playlist?list=PLRDl2inPrWQW1QSWhBU0ki-jq_uElkh2a
</div>
<div class="alert alert-block alert-info">
<b>Комментарий студента:</b> Круто! Обязательно посмотрю все ссылки!
    
    Виктория, спасибо тебе огромное!) Испытываю белую зависть к твоим коллегам, за то, что они знакомы с таким грамотным специалистом и приятным человеком😊
</div>

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера V.2👍:</b> Спасибо большое за такие тёплые слова, удачи в будущих проектах и работе =)
</div>